### ISSUE TITLE
[begrepsregistrering] Feiler med internal server error ved endring av "forhold til kilde"

### ISSUE THREAD

**Issue by stigbd** [Informasjonsforvaltning/fdk-issue-tracker#250]
begreps-id: https://registrering-begrep.fellesdatakatalog.digdir.no/991825827/e51d808c-f6f9-45f6-939f-b36b446760ba
{timestamp: "2021-03-29T06:57:10.244+0000", status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
message: "Invalid patch operation. Begrep id e51d808c-f6f9-45f6-939f-b36b446760ba"
path: "/begreper/e51d808c-f6f9-45f6-939f-b36b446760ba"
status: 500
timestamp: "2021-03-29T06:57:10.244+0000"

![image](https://user-images.githubusercontent.com/1702357/112798433-2b773600-906d-11eb-9063-7ef86a7602dd.png)

**Comment by stigbd** [comment]
I loggen til concept-catalogue:
```
jsonPayload: {
logger_name: "org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]"
timestamp: "2021-03-29T08:57:10.242+02:00"
stack_trace: "j.l.RuntimeException: Invalid patch operation. Begrep id e51d808c-f6f9-45f6-939f-b36b446760ba
	at n.b.c.BegreperApiImplK.setBegrepById(BegreperApiImplK.kt:173)
	at n.b.c.BegreperApiImplK$$FastClassBySpringCGLIB$$ba33d96d.invoke(<generated>)
	at o.s.c.p.MethodProxy.invoke(MethodProxy.java:218)
	at o.s.a.f.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
	at o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at o.s.v.b.MethodValidationInterceptor.invoke(MethodValidationInterceptor.java:119)
	at o.s.a.f.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at o.s.a.f.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
	at n.b.c.BegreperApiImplK$$EnhancerBySpringCGLIB$$94b91726.setBegrepById(<generated>)
	at s.r.GeneratedMethodAccessor127.invoke(Unknown Source)
	at s.r.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at j.l.reflect.Method.invoke(Method.java:498)
	at o.s.w.m.s.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at o.s.w.m.s.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at o.s.w.s.m.m.a.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at o.s.w.s.m.m.a.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at o.s.w.s.m.m.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at o.s.w.s.DispatcherServlet.doDispatch(DispatcherServlet.java:1039)
	at o.s.w.s.DispatcherServlet.doService(DispatcherServlet.java:942)
	at o.s.w.s.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at o.s.w.s.FrameworkServlet.service(FrameworkServlet.java:879)
	at j.s.http.HttpServlet.service(HttpServlet.java:741)
	at o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.j...
"
message: "Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: Invalid patch operation. Begrep id e51d808c-f6f9-45f6-939f-b36b446760ba] with root cause"
stack_hash: "6362fab5"
```
