### ISSUE TITLE
Feilmelding demoløsning - registrering begreper

### ISSUE THREAD

**Issue by Te-Bert** [Informasjonsforvaltning/fdk-issue-tracker#427]
Når jeg har logget inn i demoløsningen for registering og velger begrepskatalogen får jeg følgende feilmelding:
--------
Something went wrong

TypeError: Cannot read properties of null (reading 'major')

Detaljer
    at https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.82cb67740a41631219dc.js:61:37
    at e (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.react-router.4f4a041f.bundle.js:1:4276)
    at div
    at V (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.82cb67740a41631219dc.js:71:1039)
    at div
    at div
    at j (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.styled-components.493cc4b8.bundle.js:1:14913)
    at main
    at j (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.styled-components.493cc4b8.bundle.js:1:14913)
    at https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.82cb67740a41631219dc.js:99:37
    at https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.82cb67740a41631219dc.js:213:934
    at t (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.react-resolver.d7bc51c2.bundle.js:1:3584)
    at s (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.react-resolver.d7bc51c2.bundle.js:1:1590)
    at https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.82cb67740a41631219dc.js:213:710
    at https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.recompose.bd9cc342.bundle.js:1:1032
    at n (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.react-router.4f4a041f.bundle.js:1:2786)
    at n (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.react-router.4f4a041f.bundle.js:1:3736)
    at kt (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.82cb67740a41631219dc.js:213:4035)
    at n (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.react-router.4f4a041f.bundle.js:1:1127)
    at e (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.react-router-dom.7fe5df24.bundle.js:1:915)
    at yr
    at Or (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.82cb67740a41631219dc.js:291:1760)
    at Tt (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.styled-components.493cc4b8.bundle.js:1:12976)
    at Q (https://registrering-begrep.demo.fellesdatakatalog.digdir.no/main.vendor.fellesdatakatalog.44ecf4c8.bundle.js:1:9853)

**Comment by joebrreg** [comment]
Dette gjelder også prod. Testet i Edge og Chrome, får feilmelding i begge.
