### ISSUE TITLE
Frontendfeil hvis forhåndsvisning ikke finnes for datasett

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#456]
Dukket opp en ny frontendfeil.
Viser seg å bli trigget av å klikke på "Se forhåndsvisning" for en distribusjon.
Antakeligvis distribusjoner som fdk-dataset-preview-service ikke har klart å hente. 
Det at hentingen har feilet kan være relatert til #454

![image.png](https://images.zenhubusercontent.com/5da70fe359191331a197eae1/a94bd29b-df2f-4ecb-99b0-5dac22e7a6f0)

Observert på følgende datasett:
https://data.norge.no/datasets/9d082918-e3d4-4ae2-8efd-e7d025dfd52d
https://data.norge.no/datasets/e2a0e52c-3fdf-4115-b66a-eb425dcd3d7c
https://data.norge.no/datasets/dd05acaa-1c89-4139-8612-0ad10e75d6a6

Stacktrace for nr1:

`jsonPayload: {
application: "fdk-portal"
image: "37f3a2c0088a0583d87ecda255fefd0935cc7a7a"
location: "https://data.norge.no/datasets/9d082918-e3d4-4ae2-8efd-e7d025dfd52d"
message: "Cannot read properties of null (reading 'header')"
name: "TypeError"
namespace: "prod"
trace: "
    at f (https://data.norge.no/35627.5780c5d873c26a902528.js:1:10995)
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at h (https://data.norge.no/84477.686ef91c849995644fa7.js:1:4203)
    at div
    at P (https://data.norge.no/71893.1f6d9f8b44ef5b94cf41.js:1:14716)
    at div
    at P (https://data.norge.no/71893.1f6d9f8b44ef5b94cf41.js:1:14716)
    at x (https://data.norge.no/84477.686ef91c849995644fa7.js:1:4345)
    at P (https://data.norge.no/71893.1f6d9f8b44ef5b94cf41.js:1:14716)
    at H (https://data.norge.no/35627.5780c5d873c26a902528.js:1:1370)
    at section
    at P (https://data.norge.no/71893.1f6d9f8b44ef5b94cf41.js:1:14716)
    at u (https://data.norge.no/49222.f9598aa6d6ce5858cabb.js:1:2161)
    at main
    at P (https://data.norge.no/71893.1f6d9f8b44ef5b94cf41.js:1:14716)
    at div
    at P (https://data.norge.no/71893.1f6d9f8b44ef5b94cf41.js:1:14716)
    at article
    at P (https://data.norge.no/71893.1f6d9f8b44ef5b94cf41.js:1:14716)
    at N (https://data.norge.no/49222.f9598aa6d6ce5858cabb.js:1:8175)
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at t
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at ke (https://data.norge.no/71893.1f6d9f8b44ef5b94cf41.js:1:12794)
    at U (https://data.norge.no/75975.b05cb60eb01ed43896fa.js:1:1390)
    at ErrorBoundary (https://data.norge.no/41492.24c379f77c3228a3b1cf.js:1:16309)
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at t
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at t
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at t
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at t
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at t
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at n (https://data.norge.no/71338.579d087e3f781c39a746.js:1:7450)
    at n (https://data.norge.no/71338.579d087e3f781c39a746.js:1:9481)
    at ScrollToTop (https://data.norge.no/41598.460fb72aca3353570be4.js:1:3029)
    at e (https://data.norge.no/71338.579d087e3f781c39a746.js:1:10028)
    at n (https://data.norge.no/71338.579d087e3f781c39a746.js:1:9481)
    at div
    at F (https://data.norge.no/2936.c0f64b38e0ebd851852d.js:1:521)
    at ErrorBoundary (https://data.norge.no/41492.24c379f77c3228a3b1cf.js:1:16309)
    at O (https://data.norge.no/59547.e59877dd05314a821100.js:1:2561)
    at n (https://data.norge.no/71338.579d087e3f781c39a746.js:1:7450)
    at n (https://data.norge.no/71338.579d087e3f781c39a746.js:1:4056)
    at n (https://data.norge.no/73727.860bcf7a9378b848b791.js:1:947)
    at c (https://data.norge.no/59547.e59877dd05314a821100.js:1:590)
    at o (https://data.norge.no/11590.ef977ebe77a1d5b85fcb.js:1:829)
    at s (https://data.norge.no/42642.a1458a0a5a162f6e22a2.js:1:1657)
    at ke (https://data.norge.no/71893.1f6d9f8b44ef5b94cf41.js:1:12794)
    at Q (https://sparql.staging.fellesdatakatalog.digdir.no/sparql/752.747fed246b3bce1a4181.js:1:9401)"
}`

**Comment by shenluna** [comment]
Dette er løst, lukker derfor saken.
