### ISSUE TITLE
Bad char in IRI - fdk-dataset-harvester - Digdir

### ISSUE THREAD

**Issue by valosnah** [Informasjonsforvaltning/fdk-issue-tracker#642]
Det ser ut som Digdirs katalog inneholder to datasett som ikke er i henhold til spec.

> org.apache.jena.riot.RiotException: [line: 568, col: 57] Bad character in IRI (space): <[space]...>
> 	at org.apache.jena.riot.system.ErrorHandlerFactory$ErrorHandlerStd.error(ErrorHandlerFactory.java:156)
> 	at org.apache.jena.riot.tokens.TokenizerText.error(TokenizerText.java:1332)
> 	at org.apache.jena.riot.tokens.TokenizerText.readIRI(TokenizerText.java:533)
> 	at org.apache.jena.riot.tokens.TokenizerText.parseToken(TokenizerText.java:197)
> 	at org.apache.jena.riot.tokens.TokenizerText.hasNext(TokenizerText.java:93)
> 	at org.apache.jena.atlas.iterator.PeekIterator.fill(PeekIterator.java:50)
> 	at org.apache.jena.atlas.iterator.PeekIterator.next(PeekIterator.java:92)
> 	at org.apache.jena.riot.lang.LangEngine.nextToken(LangEngine.java:98)
> 	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:351)
> 	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:345)
> 	at org.apache.jena.riot.lang.LangTurtleBase.triplesBlankNode(LangTurtleBase.java:502)
> 	at org.apache.jena.riot.lang.LangTurtleBase.triplesBlankNode(LangTurtleBase.java:496)
> 	at org.apache.jena.riot.lang.LangTurtleBase.triplesNodeCompound(LangTurtleBase.java:484)
> 	at org.apache.jena.riot.lang.LangTurtleBase.triplesNode(LangTurtleBase.java:469)
> 	at org.apache.jena.riot.lang.LangTurtleBase.objectList(LangTurtleBase.java:419)
> 	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectItem(LangTurtleBase.java:352)
> 	at org.apache.jena.riot.lang.LangTurtleBase.predicateObjectList(LangTurtleBase.java:345)
> 	at org.apache.jena.riot.lang.LangTurtleBase.triples(LangTurtleBase.java:314)
> 	at org.apache.jena.riot.lang.LangTurtleBase.triplesSameSubject(LangTurtleBase.java:178)
> 	at org.apache.jena.riot.lang.LangTurtle.oneTopLevelElement(LangTurtle.java:46)
> 	at org.apache.jena.riot.lang.LangTurtleBase.runParser(LangTurtleBase.java:79)
> 	at org.apache.jena.riot.lang.LangBase.parse(LangBase.java:43)
> 	at org.apache.jena.riot.RDFParserRegistry$ReaderRIOTLang.read(RDFParserRegistry.java:199)
> 	at org.apache.jena.riot.RDFParser.read(RDFParser.java:420)
> 	at org.apache.jena.riot.RDFParser.parseNotUri(RDFParser.java:406)
> 	at org.apache.jena.riot.RDFParser.parse(RDFParser.java:356)
> 	at org.apache.jena.riot.RDFParserBuilder.parse(RDFParserBuilder.java:568)
> 	at org.apache.jena.riot.RDFDataMgr.parseFromReader(RDFDataMgr.java:728)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:287)
> 	at org.apache.jena.riot.RDFDataMgr.read(RDFDataMgr.java:271)
> 	at org.apache.jena.riot.adapters.RDFReaderRIOT.read(RDFReaderRIOT.java:62)
> 	at org.apache.jena.rdf.model.impl.ModelCom.read(ModelCom.java:246)
> 	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.rdf.RDFUtilsKt.parseRDFResponse(RDFUtils.kt:46)
> 	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.harvester.DatasetHarvester.harvestDatasetCatalog(DatasetHarvester.kt:67)
> 	at no.digdir.informasjonsforvaltning.fdk_dataset_harvester.harvester.HarvesterActivity$initiateHarvest$1$1$3$1.invokeSuspend(HarvesterActivity.kt:46)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:749)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
> Harvest of https://registrering.fellesdatakatalog.digdir.no/catalogs/991825827 failed

**Comment by KjerstiSteien** [comment]
@KurtStian er dette noe vi kan fikse på vegne av Digdir? Og kan du lære meg hvordan?

**Comment by KurtStian** [comment]
> @KurtStian er dette noe vi kan fikse på vegne av Digdir? Og kan du lære meg hvordan?

@KjerstiSteien  Denne er nok løst for lenge siden. Høstingen av Digdir datakatalog fungerer som normalt:
![image](https://github.com/Informasjonsforvaltning/fdk-issue-tracker/assets/43232700/68218e4e-f2e4-4865-8822-fa153047c641)

**Comment by KjerstiSteien** [comment]
Kurt Stian har bekreftet at denne saken er løst.
